### PR TITLE
Fix receiving empty files (#174)

### LINKED ISSUE #174: Get an empty file when the image is sent from bot and saved
```ts
import { FileBox } from "file-box";
import {WechatyBuilder,Message} from "wechaty"
import {generate} from "qrcode-terminal"
const bot=WechatyBuilder.build({puppet:'wechaty-puppet-wechat',name:'db'});

bot.on('scan',code=>generate(code,{small:true}))
.on('message',async(msg:Message)=>{
    const target=msg.room()||msg.listener();
    if(target){
        if(msg.type()==bot.Message.Type.Text){
            const text=msg.text();
            if(/pdf/i.test(text)){
                console.log(`正在发送PDF`);
                const file=FileBox.fromFile("test.pdf");
                await target.say(file)
                console.log(`PDF发送完成`);
            }else if(/image/.test(text)){
                console.log(`正在发送图片`);
                const file=FileBox.fromFile("test.png");
                await target.say(file);
                console.log(`图片发送完成`);
            }
        }else if(msg.type()==bot.Message.Type.Image){
            const file=await msg.toFileBox();
            console.log(`收到图片:${file.name}`)
            const path="received-"+file.name;
            await file.toFile(path);
            console.log(`保存图片:${path}`)
        }
    }
});
bot.start();
```
### Steps to reproduce
0.`npm install wechaty wechaty-puppet-wechat file-box qrcode-terminal`
1. Copy any image as  `test.png` in current directory
2. Run this code
3. Sent a text message `image` from WeChat client to anywhere.
4. Your WeChat client will receive an image from bot, and bot will save the image to `received-test.png` in current directory.
5. [BUG] The `received-test.png`  is a empty file

### PR DESCRIPTION
**Pull request by System233**
Fix #174 
ref #180 
`MsgId` may change after `postMessage` succeeds, and the local `MsgId` is invalid in this case.
image

https://github.com/wechaty/puppet-wechat/blob/1442099e5cbf107d97f11e99f3dee2e793260aa8/src/puppet-wechat.ts#L1144

### CODE REVIEW

File: src/puppet-wechat.ts [hunk 1]
```diff
@@ -317,9 +318,16 @@ export class PuppetWeChat extends PUPPET.Puppet {
...
 
   override async messageFile (messageId: string): Promise<FileBoxInterface> {
-    const rawPayload = await this.messageRawPayload(messageId)
-    const fileBox    = await this.messageRawPayloadToFile(rawPayload)
-    return fileBox
+    do {
+      const rawPayload = await this.messageRawPayload(messageId)
+      switch (rawPayload.MMStatus) {
+        case WebMessageStatus.SENDING:
+          await new Promise((resolve) => setTimeout(resolve, 50))
```
Comment (huan) [inline src/puppet-wechat.ts:325]: How can we know the `SENDING` will be finished after 50ms?

Is there a better way, for example, an event to let us know the `SENDING` has been finished?

Comment (System233) [reply src/puppet-wechat.ts:325]: `50ms` is the polling frequency, it runs in a loop.
I have another solution, using `setter` on `MsgId` property to hook the `MMStatus` change event, but I can't make sure it works stably.

Comment (huan) [reply src/puppet-wechat.ts:325]: If I'm understanding correctly, the `50ms` is the long polling interval of the webwx-app itself? Could you please help me to point out the related code in the webwx-app?

And if so, I think the current solution in the PR is acceptable by adding some comments to explain the `50ms` pooling interval with the related source code link (the [webwx-app-tracker](https://github.com/wechaty/webwx-app-tracker) link will be recommended).

After the comments have been added, we can merge this PR first and keep trying to improve it in the future.

Comment (System233) [reply src/puppet-wechat.ts:325]: Unfortunately it is a custom interval, plz don't merge now, let me try `root:msgSend:success` event.

Comment (huan) [reply src/puppet-wechat.ts:325]: Great, I agree that the `root:msgSend:success` event will be the solution to this workaround.

Looking forward to your update, thank you very much!

Comment (System233) [reply src/puppet-wechat.ts]: `root:msgSend:success` event only emit on message success, await it may cause deadlock when message fails, but I found `$watch` to implement it.

File: src/web-schemas.ts [hunk 2]
```diff
@@ -156,7 +156,22 @@ export enum WebAppMsgType {
...
+ * WebMessageSendStatus from webwx-app
+ *  @see https://github.com/wechaty/webwx-app-tracker/blob/a12c78fb8bd7186c0f3bb0e18dd611151e6b8aac/formatted/webwxApp.js#L7520-L7524
+ *
+ *  //msg send status
+ *    MSG_SEND_STATUS_READY: 0
+ *    MSG_SEND_STATUS_SENDING: 1
+ *    MSG_SEND_STATUS_SUCC: 2
+ *    MSG_SEND_STATUS_FAIL: 5
+ */
+export enum WebMessageSendStatus{
```
Comment (huan) [inline src/web-schemas.ts:169]: Could you please rename `WebMessageSendStatus` to `MsgSendStatus` so that it will follow the webwx-app naming convention?

**Review by huan — APPROVED** [review]
LGTM

This PR is good to be merged after the name convention has been satisfied.

Thank you very much for fixing/enhancing the file message processing logic!

File: src/web-schemas.ts (hunk 2 above)
Comment (System233) [reply src/web-schemas.ts]: Sure.

**Comment by huan** [comment]
Thank you very much for the fix!

The code will be published with `wechaty-puppet-wechat@1.11.5` and above versions.
